### ISSUE TITLE
Use spaCy instead of CoreNLP

### ISSUE THREAD

**Issue by mhillebrand** [serenayj/ABCD-ACL2021#2]
This project is awesome! However, I'd really like to test it out with spaCy instead of CoreNLP. I'm a huge fan of spaCy...and not a huge fan of Java. I see some comments in the code here and there for tips on using spaCy, but they're somewhat incomplete. Any chance you could offer a bit more guidance?

Heh, I tried to get CoreNLP configured to reverse engineer how to use spaCy instead, but their download server is out of commission:

![image](https://user-images.githubusercontent.com/286198/128412666-da82fe0a-84f4-4042-8ac9-37696b4e651b.png)

**Comment by serenayj** [comment]
Hi,

Thank you for your interest in our work! 

You are free to use whatever dependency parser you prefer. In process_data.py, you will see a GetDeps function. This is where ABCD reads in the XML format dependency parsing and converts them into a triple: (head, dep, arc). As long as you could extract dependency tags, you could modify this function to fit your preference of dependency parser. 

I could add an enhanced function to use Spacy, but I vaguely remember the reasons I did not pick spaCy over coreNLP are two-folds: 1) I didn't find the enhanced version of dependency parsing ; 2) the output format is a bit hard to deal with. Maybe I had the wrong impression. I could look into it more but it won't be added into the repository anytime soon. 
  
I'm not familiar with the reverse engineer of CoreNLP . But the download link shown in my readme seems working fine. I don't think it involves too much Java works, except with only one command.

**Comment by mhillebrand** [comment]
Yes, the CoreNLP download server is finally [back up](https://github.com/stanfordnlp/CoreNLP/issues/1172). I got it installed & working, but I can't believe it takes CoreNLP over 12 seconds to load before doing any work...on a seriously **beefy** machine.

Here is what I can produce with spaCy:

```
prep(broken-10, Despite-0)
compound(attempts-2, police-1)
pobj(Despite-0, attempts-2)
aux(maintain-4, to-3)
acl(attempts-2, maintain-4)
dobj(maintain-4, order-5)
punct(broken-10, ,-6)
nummod(apartments-8, ten-7)
nsubjpass(broken-10, apartments-8)
auxpass(broken-10, were-9)
ROOT(broken-10, broken-10)
prep(broken-10, into-11)
punct(broken-10, ,-12)
nummod(people-14, nineteen-13)
nsubjpass(injured-16, people-14)
auxpass(injured-16, were-15)
conj(broken-10, injured-16)
punct(injured-16, ,-17)
cc(injured-16, and-18)
det(kitchen-22, the-19)
amod(kitchen-22, Jewish-20)
compound(kitchen-22, community-21)
nsubjpass(ransacked-24, kitchen-22)
auxpass(ransacked-24, was-23)
conj(injured-16, ransacked-24)
punct(ransacked-24, .-25)
```

Here's what CoreNLP creates:

```
root(ROOT-0, broken-11)
mark(maintain-5, Despite-1)
compound(attempts-3, police-2)
nsubj(maintain-5, attempts-3)
mark(maintain-5, to-4)
advcl:to(broken-11, maintain-5)
obj(maintain-5, order-6)
punct(broken-11, ,-7)
nummod(apartments-9, ten-8)
nsubj:pass(broken-11, apartments-9)
aux:pass(broken-11, were-10)
case(injured-17, into-12)
punct(injured-17, ,-13)
nummod(people-15, nineteen-14)
nsubj:pass(injured-17, people-15)
aux:pass(injured-17, were-16)
obl:into(broken-11, injured-17)
punct(broken-11, ,-18)
cc(ransacked-25, and-19)
det(kitchen-23, the-20)
amod(kitchen-23, Jewish-21)
compound(kitchen-23, community-22)
nsubj:pass(ransacked-25, kitchen-23)
aux:pass(ransacked-25, was-24)
conj:and(broken-11, ransacked-25)
punct(broken-11, .-26)
```

I'm currently reading about the enhanced and enhanced++ representations in [this paper](http://nlp.stanford.edu/~sebschu/pubs/schuster-manning-lrec2016.pdf). Do you think it's absolutely necessary?
