### ISSUE TITLE
GPU utilization

### ISSUE THREAD

**Issue by mhillebrand** [serenayj/ABCD-ACL2021#3]
I noticed that, while training on my own dataset, GPU utilization fluctuates wildly between 20% and 60%. I'm guessing that's because most of the data exists on the CPU, in the form of dictionaries—rather than PyTorch tensors on the GPU. 

<img width="809" alt="Screen Shot 2021-09-08 at 7 49 24 PM" src="https://user-images.githubusercontent.com/286198/132762552-09128ba2-42d1-46b6-bbc1-860dad54ccad.png">

It doesn't look like Networkx/DGL are really being used for training. For example, in `data.py`, the graph object created in `__getitem__` isn't being used. Then a comment towards the end says, "keeping the graph structure as dictionary."

```	
    def __getitem__(self, idx):
        sample = {}
        item = self.data[idx]
        words = item['words']
        all_pairs = item['all_pairs']
        adjs = item['adjs']
        # graph = BuildGraph(adjs)
        a, b, c, d = item['accept'], item['break'], item['copy'], item['drop']
        gold = item['golds']
        gold_pairs, gold_labels = GoldLabel(all_pairs, a, b, c, d)
        pair_arcs = GetArc(all_pairs, self.arc_one_dics, self.label_arcs, self.use_cuda)
        vecs = self.sent_vecs[idx]
        vecs.cuda() # L X D
        sample['sent'], sample['itov'], sample['gold_sent'] = vecs, item['itov'], gold
        sample['a'], sample['b'], sample['c'], sample['d'] = a, b, c, d
        sample['all_words'] = words
        sample['pair_vecs'], sample['adj_pairs'] = pair_arcs, all_pairs
        sample['gold_pairs'] = gold_pairs
        sample['adj'] = adjs # keeping the graph structure as dictionary
        gold_labels = gold_labels.cuda()
        sample['gold_labels_tensor'] = gold_labels

        return sample
```

I'd really like to try training an ABCD model using multiple GPUs, but I can't until I get all this data on the GPU. What do you recommend I do? Shall I read the DGL documentation and go that route?

**Comment by serenayj** [comment]
Hi, 

ABCD implementation is currently not supported by multi-GPU. If you really want to do so, you could convert the dictionary into some networkx cuda graphs with different attributes as edge or node attributes (https://docs.rapids.ai/api/cugraph/stable/nx_transition.html). But then since a sentence is a graph you would get many networkx graphs.  You will also need to modify the training and test setting.

**Comment by mhillebrand** [comment]
Okay, I might just give that a shot. Thank you.
