### ISSUE TITLE
Key Error: nsubjpass

### ISSUE THREAD

**Issue by insundaycathy** [serenayj/ABCD-ACL2021#4]
While running test.py, I keep getting this error message. 
 File "test.py", line 67, in <module>
    sample = test_db[_k]
  File "/export/home/yidansun/ABCD-ACL2021/data.py", line 244, in __getitem__
    pair_acs = GetArc(all_pairs, self.arc_one_dics, self.label_arcs, self.use_cuda)
  File "/export/home/yidansun/ABCD-ACL2021/data.py", line 61, in GetArc
    arc_onehot = torch.tensor(one_arcs[label_arcs[arc.split(":")[0]]]).unsqueeze(0)
KeyError: 'nsubjpass'

**Comment by serenayj** [comment]
Hi, 

Are you using the pre-trained model? If so it could be that the passive form of "nsubj" is not encountered in the corpus I have for pre-trained model. There are two solutions:
1. Change nsubjpass to nsubj in the data.py. (Just to add an if-else statement that change any passive forms to active, e.g. csubjpass- csubj). This is recommended as nsubj and nsubjpass showing the same semantic subject. 
or 2. You could add the nsubjpass into arcs as a new key, and train your data that way (if you have the training set).    

Hope this helps.

**Comment by insundaycathy** [comment]
Thank you, this is very helpful. and yes, I think it was because I'm using the pretrained model. I changed it to 'nsubj' and everything worked perfectly. Thank you.
________________________________
